### ISSUE TITLE
Animating elements on the same line

### ISSUE THREAD

**Issue by Fingerflow** [maciekgrzybek/svelte-inview#3]
Hi, thanks for this helpful svelte component. 
It seems that elements are ignored when they share Y position with other. In other words if you have 2 <div> on the same line, only one will be animated. I'll start digging in the codebase to see if I can detect the reason.

**Comment by maciekgrzybek** [comment]
Hey @Fingerflow, thanks for cresting this issue. Could you show an example of the problem? I'll have some time this weekend, I will take a look :)

**Comment by maciekgrzybek** [comment]
Spoke with @Fingerflow , turns out it wasn't a problem with the package but with something else.
