### ISSUE TITLE
Support Svelte v4

### ISSUE THREAD

**Issue by bartveneman** [maciekgrzybek/svelte-inview#43]
Currently Svelte is listed as a peerDependency with version `^3.0.0`. It would be nice to start testing with [Svelte 4 (beta)](https://github.com/sveltejs/svelte/blob/version-4/packages/svelte/CHANGELOG.md#400-next0) to check if there's any breaking changes. If all works, maybe v4 can be added to the list of supported peerDependencies.

**Comment by maciekgrzybek** [comment]
Hey @bartveneman that's a good idea. I'm a little short on the free time recently, you fancy to test it and create PR? :)

**Comment by bartveneman** [comment]
I'll give it a try 👍
