### ISSUE TITLE
Uncaught TypeError: Cannot read property 'unobserveOnEnter' of undefined

### ISSUE THREAD

**Issue by danawoodman** [maciekgrzybek/svelte-inview#9]
Hello! 

I'm noticing the following error when the user scrolls out of focus for an item:

![image](https://user-images.githubusercontent.com/157695/130286680-c3997213-31fd-41e6-a075-043239f37bb3.png)

I don't have an `on:leave` event, code is basically:

```html
<div use:inview on:enter={({ detail: { inView } }) => (isInView = inView)}>
  {#if isInView}
    Stuff here...
  {/if}
</div>
```

Using latest version.

Any idea why this is occurring?

**Comment by maciekgrzybek** [comment]
Hey @danawoodman this should be fixed in the newest version of this package 😊
